### ISSUE TITLE
CopyEventPlugin not working as expected

### ISSUE THREAD

**Issue by dsepulvedar** [raizdev/schedule-x-plugins#2]
I'm using the example at https://starredev.github.io/schedule-x-plugins/. I right-click and then drag, it gives me the feedback that the event will be copied once released into the new time slot, but it doesn't. I open the console to see if the event was printed but it wasn't, as expected based on the example code at https://github.com/starredev/schedule-x-plugins/blob/main/example/src/App.vue#L42.

Similarly, in my application, which looks like follows:
```
import { useCalendarApp, ScheduleXCalendar } from '@schedule-x/react'
import { viewWeek } from '@schedule-x/calendar'
import { createDragAndDropPlugin } from '@schedule-x/drag-and-drop'
import { createScrollControllerPlugin } from '@schedule-x/scroll-controller'
import { createEventModalPlugin } from '@schedule-x/event-modal'
import { createEventsServicePlugin } from '@schedule-x/events-service'
import { createResizePlugin } from '@schedule-x/resize'
import { createCalendarControlsPlugin } from '@schedule-x/calendar-controls'
import { CopyEventPlugin } from '@starredev/schedule-x-plugins'

import CustomEventModal from './components/CustomEventModal'
import './App.css'

const eventsServicePlugin = createEventsServicePlugin();
const eventModalPlugin = createEventModalPlugin();
const calendarControlsPlugin = createCalendarControlsPlugin();

function App() {

  const calendarApp = useCalendarApp({
    views: [viewWeek],
    events: [
      {
        id: '1',
        title: 'Event 1',
        start: '2025-06-07 09:00',
        end: '2025-06-07 10:00'
      }
    ],
    callbacks: {
      onClickDateTime: (dateTime) => {
        // Create a new event with 1-hour duration
        const startDateTime = new Date(dateTime);
        const endDateTime = new Date(startDateTime.getTime() + 60 * 60 * 1000); // Add 1 hour

        const newEvent = {
          id: Date.now().toString(), // Simple ID generation
          title: '',
          start: startDateTime.toISOString().slice(0, 16), // Format: YYYY-MM-DDTHH:mm
          end: endDateTime.toISOString().slice(0, 16)
        };

        // Open the event modal with the new event
        eventModalPlugin.setCalendarEvent(newEvent, null);
      },
      onEventUpdate(updatedEvent) {
        console.log('onEventUpdate', updatedEvent)
      }
    },
    plugins: [
      createScrollControllerPlugin(),
      calendarControlsPlugin,
      eventModalPlugin,
      eventsServicePlugin,
      new CopyEventPlugin(eventsServicePlugin, event => {
        console.log('CopyEventPlugin', event);
        eventsServicePlugin.add(event);
    })
    ]
  });

  const handleCloseModal = () => {
    eventModalPlugin.close();
  };

  const customComponents = {
    eventModal: ({calendarEvent}) => {
      return <CustomEventModal
        calendarEvent={calendarEvent}
        onClose={handleCloseModal}
        eventsService={eventsServicePlugin}
      />
    }
  };

  return (
    <div className="calendar">
      <ScheduleXCalendar
        calendarApp={calendarApp}
        customComponents={customComponents}
      />
    </div>
  )
}

export default App

```

I can't even get the feedback that the right-click + drag gives in the example.

Your help will be appreciated

**Comment by starredev** [comment]
so on https://starredev.github.io/schedule-x-plugins/ it isn't working either? Which browser are u using?

**Comment by dsepulvedar** [comment]
Correct, it isn't working in https://starredev.github.io/schedule-x-plugins/
I tested it in Firefox and Chrome.

I'm now thinking that I might be unaware of the right expectation. Mine is that after right-click+drag, then released in a new slot, the event is copied/created in that time slow.

**Comment by starredev** [comment]
> Correct, it isn't working in https://starredev.github.io/schedule-x-plugins/ I tested it in Firefox and Chrome.
> 
> I'm now thinking that I might be unaware of the right expectation. Mine is that after right-click+drag, then released in a new slot, the event is copied/created in that time slow.

the correct expectation is 

Right-click (and release immediately on the original event) → a placeholder appears, indicating the event is now "held" →
Then left-click anywhere else on the calendar to paste it.

![Image](https://github.com/user-attachments/assets/75dea80a-d8e7-477d-ad28-52a007810535)

For me on both browser it is working as expected

**Comment by dsepulvedar** [comment]
I was missing the left-click anywhere else on the calendar to paste it. I thought it was only a matter of dropping (releasing the right-click) and that would paste. On top of it, I was trying it with the trackpad which probably isn't implemented, but with the mouse, it works. 

I'm now going to try with my own App to see if I can get the same result.

**Comment by starredev** [comment]
> I was missing the left-click anywhere else on the calendar to paste it. I thought it was only a matter of dropping (releasing the right-click) and that would paste. On top of it, I was trying it with the trackpad which probably isn't implemented, but with the mouse, it works.
> 
> I'm now going to try with my own App to see if I can get the same result.

I haven't tested it with trackpad, I can look into that later today!

Providing a fallback UI button like "Copy mode" → click an event → select drop location, could be an option since trackpad doesn't have physical right-click release

If you have any ideas on how the copy plugin could work better, feel free to let me know.
To me, the current behavior of the events felt like the most intuitive approach so far.

**Comment by dsepulvedar** [comment]
I've been trying to make it work in my React app but with no avail. I even removed all Plugins and only left yours, CopyEventPlugin. Still it doesn't work. 

Would you mind having a look at the initial code? Currently, it is very similar but only with your plugin, and of course the required one eventsServicePlugin and calendarControlsPlugin.

**Comment by starredev** [comment]
> I've been trying to make it work in my React app but with no avail. I even remove all Plugins and only left yours, CopyEventPlugin. Still it doesn't work.
> 
> Would you mind having a look at the initial code? Currently, it is very similar but only with your plugin, and of course the required one eventsServicePlugin and calendarControlsPlugin.

I haven't test it on React to be honest, only on VueJS. Will look into it today

**Comment by starredev** [comment]
@dsepulvedar id is an string, it should be an integer otherwise schedule-x eventService will not retrieve the object. 

````
events: [
      {
        id: 1,
        title: 'Event 1',
        start: '2025-06-07 09:00',
        end: '2025-06-07 10:00'
      }
    ],
````

Pushed fix: [1.6.1](https://www.npmjs.com/package/@starredev/schedule-x-plugins/v/1.6.1)

**Comment by dsepulvedar** [comment]
Thank you! Changed it to integer and it now works. Great catch. 

By the way, just a final comment: the Plugin collides with the native createDragAndDropPlugin, so they cannot be used together. 

I'll continue my work but I won't forget about comment with respect to the expect trackpad behavior.

**Comment by starredev** [comment]
> Thank you! Changed it to integer and it now works. Great catch.
> 
> By the way, just a final comment: the Plugin collides with the native createDragAndDropPlugin, so they cannot be used together.
> 
> I'll continue my work but I won't forget about comment with respect to the expect trackpad behavior.

I see, because of duplicate id's. I could fix that too in next release

**Comment by starredev** [comment]
@dsepulvedar i've pushed fix for the collision with drag and drop plugin.

**Comment by dsepulvedar** [comment]
@starredev that's wonderful. I'm at work now. I'll give it a try later today, probably at night.

**Comment by starredev** [comment]
> [@starredev](https://github.com/starredev) that's wonderful. I'm at work now. I'll give it a try later today, probably at night.

you have tested it?

**Comment by dsepulvedar** [comment]
Hello @starredev apologies for the late reply. 
I have now been able to test. While it has improved, I think it is still colliding. I have the DragAndDropPlugin enabled (this is in my React App, I should test with a more lighter example to reduce noise, but... well this should also work in more robust scenarios). What I'm finding when having both the DragAndDropPlugin and CopyEventPlugin active is that the event gets copied and moved at the same.
The below attached video show that when I right-click and start dragging there's the event held because of your Plugin, but also for the DragAndDropPlugin. When I then left-click, the event is copied but also the original is moved. 

https://github.com/user-attachments/assets/379a4ba4-d452-40e8-a9cc-77d7c3a693cb

Furthermore, I did an additional test where I'm NOT using the DragAndDropPlugin, only your CopyEventPlugin. What happens is that a copied event cannot be copied again, only the original one. 
I should say this **only** happens in my React App, where I'm using additional plugins and also a customEventModal. 
Further clarification: in your example, copied events CAN be copied from again. 

Basically, I'm pointing out a problem with my app, that I should investigate further. 

Please let me know if I'm being clear.

**Comment by starredev** [comment]
> The below attached video show that when I right-click and start dragging there's the event held because of your Plugin, but also for the DragAndDropPlugin. When I then left-click, the event is copied but also the original is moved.

Are you holding the right mouse button? You need to release it.

> Furthermore, I did an additional test where I'm NOT using the DragAndDropPlugin, only your CopyEventPlugin. What happens is that a copied event cannot be copied again, only the original one.

I've just pushed a fix — you can now also copy items that were already copied before.
This bug was introduced by a previous fix I made.

Today I'm checking both fixes in react stack, to see if its also solved there and will publish the fix afterwards

**Comment by starredev** [comment]
@dsepulvedar fix pushed. also added react example in this repository. You could play around with it if you want.

**Comment by dsepulvedar** [comment]
@starredev given that you've taken the time to do a React example, let's focus exclusively on it to get the DragAndDropPlugin and your CopyEventPlugin working together, and for the time being, eliminate my app from the equation. 

With that in mind, I've run the React and found the following:

The `"uuidv4": "^6.2.13"` dependency [here](https://github.com/starredev/schedule-x-plugins/blob/main/package.json#L50) should be updated to `"uuid": "^v11.1.0"`, otherwise, the App renders the below error:
![Image](https://github.com/user-attachments/assets/2df5dec6-6ff4-44f5-92ff-422fcf0f99d2)
After updating the package.json an reinstalling, the example worked. 
<img width="855" alt="Image" src="https://github.com/user-attachments/assets/42310af0-2462-4a75-bbb2-b9466fc19e35" />

 > Are you holding the right mouse button? You need to release it.

I'm confused here. I right-click to held the event, keep it pressed while dragging, to finally press left-click which effectively copies the event. If I simply right-click the event, the same isn't held, and I cannot drag it to place it in a new time slot.
 
I'm doing it like this because the readme says:
```
Right-click on an event to begin copy-drag
```
If I only right-click, the held event appears and then left-click, it copies the event in the same time slot as the original. After that, I can drag the copied event elsewhere with the DragAndDropPlugin. 
Is this the expected use? Because I was under the impression I could drag the held event and place somewhere else. 
**Video 1**

https://github.com/user-attachments/assets/5fc18e5c-e2ab-48cd-b59f-171f379cda75

**Video 2**

https://github.com/user-attachments/assets/9ebe5f9f-cf67-404a-b52f-c1227d8bfab3

Am I still using the click and drag gestures wrong in the second video?

An additional thought: the plugins are colliding in their click events. I don't know why the DragAndDropPlugin activates with right-click and drag. I think this is bug, don't you think? If it would only activate with left-click+drag, it wouldn't collide. 
That's my take. 

Again, I'll attentive.

**Comment by starredev** [comment]
> If I only right-click, the held event appears and then left-click, it copies the event in the same time slot as the original. After that, I can drag the copied event elsewhere with the DragAndDropPlugin.

this is exactly how it works.

as you can see in my video in the react app, I couldnt find any issues around it...

https://gyazo.com/934d885f478d37380d3763b49d375cc5

**Comment by dsepulvedar** [comment]
@starredev I'm running the React app example as is, which has both DragAndDropPlugin and CopyEventPlugin enabled. I'm on MacOS 15.5, I've tested it in Brave, Firefox and Chrome. I'm still not getting what you've shown in the video 🤷 
I'll attach a couple of videos showing what I'm getting:

In this video, I only use right-click and drag. It drags the event as if it was the DragAndDropPlugin. Here's what I'm seeing that they're colliding, because why would right-click activate the DragAndDropPlugin? 

https://github.com/user-attachments/assets/754dcb7c-046f-4ee6-b443-2646ce3a4ac7

https://github.com/user-attachments/assets/3ffdcd01-ad53-49fd-afc3-0cca9752a290

I understand you've said that I only need to right-click, release, then drag, then left-click. But If a release the right-click, I cannot drag the held event to a new slot. 

If I disabled the DragAndDropPlugin, I get exactly what you've shown in your video:

https://github.com/user-attachments/assets/5ab9c9b1-dc40-43c5-88d7-1c1baca72936

**Comment by starredev** [comment]
> I understand you've said that I only need to right-click, release, then drag, then left-click. But If a release the right-click, I cannot drag the held event to a new slot.

Right click -> release -> it holds the event automaticly and paste it in a time-slot where you want with left click.

I will modify the readme.

**Comment by dsepulvedar** [comment]
@starredev I think this is a matter of the OS. I've been testing in MacOs with no avail. I asked friends to test in Linux and Windows. The only OS where it works as you've described is Windows. Are you by chance using Windows?

I sent them the online example at https://starredev.github.io/schedule-x-plugins/, ask them to right-click and event, release right-click, drag and finally left-click. As mentioned it only worked on Windows.

**Comment by starredev** [comment]
> [@starredev](https://github.com/starredev) I think this is a matter of the OS. I've been testing in MacOs with no avail. I asked friends to test in Linux and Windows. The only OS where it works as you've described is Windows. Are you by chance using Windows?
> 
> I sent them the online example at https://starredev.github.io/schedule-x-plugins/, ask them to right-click and event, release right-click, drag and finally left-click. As mentioned it only worked on Windows.

Are u able to do PR? I don't have Mac to test and solve ...

**Comment by starredev** [comment]
Please test 1.6.4-beta.0

**Comment by dsepulvedar** [comment]
@starredev  Is it possible for you to upload the changes applied in 1.6.4-beta.0 to this Guthub repository in another branch? This would help better understand what you've done and maybe attempt to collaborate further. TBH, I'm not a full-time program, my knowledge so having a starting point helps

I have tested with 1.6.4-beta.0 (from NPM) and the issue remains for MacOS. 
To test, I have:
- Updated the React example package JSON so it includes `"@starredev/schedule-x-plugins": "1.6.4-beta.0"`
- Updated the example to change the place from where the CopyEventPlugin will be imported:
```
import { CopyEventPlugin } from '@starredev/schedule-x-plugins'
```
Instead of:
```
import { CopyEventPlugin } from '../../../src'
```

**Comment by starredev** [comment]
Should be fixed in latest commit
